### ISSUE TITLE
Question: That's unit? Byte? Megabyte?

### ISSUE THREAD

**Issue by godfreylab** [JoshSchreuder/serilog-enrichers-memory#1]
Hi there, 

I just used this tool, which is very handy! I get the number by this package. But what's unit for this number? Byte? Megabyte?
![image](https://user-images.githubusercontent.com/8380236/213060320-671a985a-f263-4a9f-b827-33fbf3f6bbd7.png)

**Comment by krzysiek-b** [comment]
The answer for your question should be in the docs for the method used here https://github.com/serilog-contrib/serilog-enrichers-memory/blob/master/src/Serilog.Enrichers.Memory/Enrichers/MemoryUsageEnricher.cs
which can be found here https://learn.microsoft.com/en-us/dotnet/api/system.gc.gettotalmemory?view=net-7.0

**Comment by godfreylab** [comment]
Thank you so much @krzysiek-b . The first link shows me it is bytes! The second link gives me a knowledge where we get this. Thank you again. It is good to learn it !
